name: MAIArchitects
favicon: null
layout_spectrum: 0.23570895637385547
typography_spectrum: 0.15144418110139668
title: 'MAIArchitects           Marcuccio - Architecture & Interior Architects'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3924616267904639
  lightness: 0.39171019080094993
  saturation: 0.7965529670473188
  rhythmicContrast: 0.27196511439979076
purpose: []
